### ISSUE TITLE
Navn på skiløyper

### ISSUE THREAD

**Issue by anderfo** [esisa/Turkompisen-kart#21]
Bør rendres med navn på Turkompisen skikart:
piste:type=\* ; name=*
F.eks. denne løypa som er tagget med name=Heiløypa: http://www.turkompisen.no/#15/63.4100/10.2286/skikart

I dag er det kun disse som får navn på kartet:
highway=\* ; name=*
F.eks. diverse løyper her: http://www.turkompisen.no/#15/63.3946/10.2225/skikart

**Comment by esisa** [comment]
Disse løypene blir nå tegna med navn på.
